function comparison(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 05-Feb-2016 13:33:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YMinorTick','on','YScale','linear',...
    'FontSize',12);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-0.25 0.05]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel({'Electron Temperature (keV)'},'FontSize',14);

% Create xlabel
xlabel({'Axial Position (cm)'},'FontSize',14);

% Create title
title({'Electron Temperature Comparison between HYADES and FLASH'},...
    'FontSize',16);

% Create semilogy
plot(X1-0.4,Y1/11.6e6,'LineWidth',2);

% Create semilogy
plot(X2,Y2,'LineWidth',2);

