function createplotComparisonfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  Y6:  vector of y data

%  Auto-generated by MATLAB on 04-Feb-2016 21:10:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YMinorTick','on','YScale','linear',...
    'FontSize',12);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-0.25 0.05]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 3]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel({'Electron Temperature (keV)'},'FontSize',14);

% Create xlabel
xlabel({'Axial Position (cm)'},'FontSize',14);

% Create title
title({'Electron Temperature Comparison between Hyades and FLASH'});

% Create plot
plot(X1,Y1/11.6e6,'DisplayName','FLASH 1.5ns','Color',[0 0.498039215803146 0]);

% Create plot
plot(X2,Y2,'DisplayName','HYADES 1.5ns','LineStyle','--',...
    'Color',[0 0.498039215803146 0]);

% Create plot
plot(X3,Y3/11.6e6,'DisplayName','FLASH 2.5ns','Color',[1 0 0]);

% Create plot
plot(X4,Y4,'DisplayName','HYADES 2.5ns','LineStyle','--',...
    'Color',[1 0 0]);

% Create plot
plot(X5,Y5/11.6e6,'DisplayName','FLASH 3.5ns',...
    'Color',[0 0.447058826684952 0.74117648601532]);

% Create plot
plot(X6,Y6,'DisplayName','HYADES 3.5ns','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.143142100400145 0.710727969348659 0.235788717209918 0.185823754789272],...
    'FontSize',10.8);

