function FLASH=FLASHcurveread(FLASH, varname, filename)
%example varnum: tele0000
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/centerforenergyresearch/Downloads/FLASH4.3/results/Oct25/eden1_5ns.curve
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/02/04 14:34:33

%% Initialize variables.
%tablename='tele0030';

%filename = ['/Users/centerforenergyresearch/Downloads/FLASH4.3/results/Oct25/',tablename,'.curve'];
%filename=['/Users/centerforenergyresearch/Downloads/FLASH4.3/results/2layerSphere/tele/2layerSphere_',tablename,'.curve'];
delimiter = ' ';
startRow = 4;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
FLASH.(varname) = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

end