intensites=[30,40,50,60,1];
varname=char('rcm','dene','rho','te');
time='3_5';
for i=2:size(varname,1)
    tablename=strcat('HotEScaleEP_16A_',varname(i,:),'_100CH_I');%,num2str(intensites),'__1_5ns');
    if i~=4

        comparisonint('log',strcat(varname(i,:)),FLASH.(strcat(varname(i,:),time,'ns'))(:,1)-0.4,...
        FLASH.(strcat(varname(i,:),time,'ns'))(:,2),...
        Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I30__',time,'ns')),Hyades.(strcat(tablename,'30__',time,'ns')),...
        Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I40__',time,'ns')),Hyades.(strcat(tablename,'40__',time,'ns')),...
        Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I50__',time,'ns')),Hyades.(strcat(tablename,'50__',time,'ns')),...
        Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I60__',time,'ns')),Hyades.(strcat(tablename,'60__',time,'ns')),...
        Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I1__',time,'ns')),Hyades.(strcat(tablename,'1__',time,'ns')))
    else
            comparisonint('lin',strcat(varname(i,:)),FLASH.(strcat(varname(i,:),time,'ns'))(:,1)-0.4,...
    FLASH.(strcat(varname(i,:),time,'ns'))(:,2)/11.6e6,...
    Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I30__',time,'ns')),Hyades.(strcat(tablename,'30__',time,'ns')),...
    Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I40__',time,'ns')),Hyades.(strcat(tablename,'40__',time,'ns')),...
    Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I50__',time,'ns')),Hyades.(strcat(tablename,'50__',time,'ns')),...
    Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I60__',time,'ns')),Hyades.(strcat(tablename,'60__',time,'ns')),...
    Hyades.(strcat('HotEScaleEP_16A_rcm_100CH_I1__',time,'ns')),Hyades.(strcat(tablename,'1__',time,'ns')))

    end

end